### ISSUE TITLE
Confirm before delete

### ISSUE THREAD

**Issue by dalinxz** [shacker/django-todo#97] opened 2020-01-24 09:11 UTC
Hey shacker, incredible work on this lightweight but powerful todo app! Thank you.

I had one suggestion for future improvements, which is to add a confirm before deleting the task. Keep it up, really appreciate the work.

**Comment by shacker** [comment] 2020-03-08 21:47
Good suggestion @dalinxz . I've retitled this issue and marked it "Good first issue" for anyone who drives by and wants to contribute the feature. Thanks.

**Comment by sum35h** [comment] 2020-12-12 17:22
Hi @dalinxz , I would like to work on this, if the issue is still open.

**Comment by shacker** [comment] 2020-12-13 20:32
Sure thing @sum35h - this still needs to be done, and I welcome your pull request any time. Thanks in advance.

**Comment by aaroosh-07** [comment] 2021-01-14 17:34
@shacker can i take up this issue

**Comment by shacker** [comment] 2021-01-15 07:25
@sum35h Have you started on this? If not, do you mind of @aaroosh-07 works on it?

**Comment by 1hanzla100** [comment] 2021-01-29 10:37
@shacker I want to fix this issue. Assign it to me

**Comment by shacker** [comment] 2021-01-30 07:03
@1hanzla100 I don't assign things here - most OSS projects don't. Either communicate with others in this thread, or just be first with a good pull request!

**Comment by EdgarPrada** [comment] 2021-07-31 22:02
This improvement is already done. -Shouldn't this be marked as closed? 
Great project. Thanks

**Comment by shacker** [comment] 2021-08-03 06:05
Thanks @EdgarPrada, right you are. Closing. Glad you enjoy the project!

**Closed by shacker** 2021-08-03 06:05 UTC
Labels: good first issue
