### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by xor0x** [shacker/django-todo#62] opened 2019-03-26 06:57 UTC
After adding a comment. I'm doing a page update is added another same comment.  If I'm write the first comment "Test" and i refresh page two times i have three comments with "test"

Example http://django-todo.org/todo/task/475682/

**Comment by xor0x** [comment] 2019-03-26 08:08
Now in new version problem with add comment.
i cant add a comment have error
ConnectionRefusedError at /todo/task/1/
[WinError 10061] No connection could be made because the target machine actively refused it

**Comment by shacker** [comment] 2019-03-27 06:57
I am having an issue with django-todo.org that may take a couple of days to work out. Sorry!

That is unrelated to your local issue, which looks like maybe your database server is not running?

**Comment by shacker** [comment] 2019-03-27 07:21
Are you using postgres version 9.3 or lower by chance? That is no longer supported by django and may be the cause of your issue (it is in fact related to the current django-todo.org downtime).

**Comment by xor0x** [comment] 2019-03-27 07:31
I'm working with SQLite. Need work with Postgres?

**Comment by xor0x** [comment] 2019-03-27 10:13
Ok. Now I'm using PostgreSQL. The problem does change. But if i'm commented this code:
    send_email_to_thread_participants(
        task,
        request.POST["comment-body"],
        request.user,
        subject='New comment posted on task "{}"'.format(task.title),
    )
in task_detail.py it is work perfectly.

**Comment by shacker** [comment] 2019-03-27 15:16
Interesting, I will do a test with sqlite to see if there is a new issue there I don't know about.

It sounds like the rest of your issue is about mail sending, rather than databases. Is your project already set up to send email, as mentioned in the documentation? A quick way to get around it would be to have email sent to the terminal rather than to a mail server. Add to settings or local settings:

`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`

**Comment by xor0x** [comment] 2019-03-27 18:51
What i need to do with this TODO_MAIL_BACKENDS and TODO_MAIL_TRACKERS please send me example how i need setap email

**Comment by shacker** [comment] 2019-03-28 06:51
Are you sure you need those? Are you actually trying to set up mail tracking? If not, then DON'T set them! 

If you *are* trying to set them up, please let us know what in the documentation is not working for you - the examples look pretty clear to me.

**Comment by xor0x** [comment] 2019-03-28 07:17
Sorry, my friend. Now it is work perfectly. I'm so stupid.

**Comment by xor0x** [comment] 2019-03-28 07:27
> After adding a comment. I'm doing a page update is added another same comment. If I'm writing the first comment "Test" and i refresh page two times i have three comments with "test"
> 
> Example http://django-todo.org/todo/task/475682/

But you have problems with comments. I'm set this script in base.html.
        <script>
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>
Now it is work perfectly.

**Comment by shacker** [comment] 2019-03-29 06:41
Sorry for the downtime on django-todo.org. The demo site is back up and running. 

What is the problem with comments? They seem fine to me, I see no errors, have never had a complaint. What does your javascript do or aim to "fix?"

Closing this as the OP was due to a documentation misunderstanding.

**Closed by shacker** 2019-03-29 06:41 UTC
