### ISSUE TITLE
pip install django-todo didn't install bleach

### ISSUE THREAD

**Issue by terencecollins** [shacker/django-todo#110] opened 2020-09-10 15:52 UTC
Not sure if it was just me, but when I had installed via pip, I later had to manually pip install bleach.

**Comment by shacker** [comment] 2020-11-01 21:47
Hi @terencecollins - I just had a second look, and confirmed that bleach is right there in the [Pipfile](https://github.com/shacker/django-todo/blob/master/Pipfile#L13), as well as in Pipfile.lock. So I am guessing that maybe you didn't install dependencies via the Pipfile? It's tricky with there being so many dependency ecosystems out there. In the next iteration, I might move to a different installation technique, since pipenv seems to be losing favor. I'm going to close this for now.

**Closed by shacker** 2020-11-01 21:47 UTC
